// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0e0nH1k4zFBosw0J6xFIn1l7pw5XR-a8',
    appId: '1:992310156694:web:664630f465d3a1778b11b7',
    messagingSenderId: '992310156694',
    projectId: 'gomodiarect-f8ae4',
    authDomain: 'gomodiarect-f8ae4.firebaseapp.com',
    storageBucket: 'gomodiarect-f8ae4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyk-dxWhmY03W_jrDAMCruwdKa0ZhY15Y',
    appId: '1:992310156694:android:fbf19d86237b92878b11b7',
    messagingSenderId: '992310156694',
    projectId: 'gomodiarect-f8ae4',
    storageBucket: 'gomodiarect-f8ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJsRZJ6_GPsVppLlhdnOAGzRcAuxM69U',
    appId: '1:992310156694:ios:4d088798b3f006ee8b11b7',
    messagingSenderId: '992310156694',
    projectId: 'gomodiarect-f8ae4',
    storageBucket: 'gomodiarect-f8ae4.appspot.com',
    iosClientId: '992310156694-flps49gh1jio01lci4mhm441i8fjjtso.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomodiarect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJsRZJ6_GPsVppLlhdnOAGzRcAuxM69U',
    appId: '1:992310156694:ios:4d088798b3f006ee8b11b7',
    messagingSenderId: '992310156694',
    projectId: 'gomodiarect-f8ae4',
    storageBucket: 'gomodiarect-f8ae4.appspot.com',
    iosClientId: '992310156694-flps49gh1jio01lci4mhm441i8fjjtso.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomodiarect',
  );
}
